### ISSUE TITLE
[Feat] EC2 메모리 문제

### ISSUE THREAD

**Issue by johan1103** [posomo/saltit-log-ec2-environment#1]
Docker Compose로 ELK 스택 및 Redis를 컨테이너로 생성해서 작동시키면 몇개의 컨테이너가 죽어버리고 EC2 자체도 엄청 느려지는 현상이 발생했습니다.

CPU 사용률이 99%까지 올라갔기 때문에 처음에는 CPU자체 성능 문제라고 생각했지만, RAM 메모리 용량을 늘려서 해결했다는 사례를 많이 찾을 수 있었습니다.

다음은 현재 작성한 Docker-compose 파일입니다. 각각의 설정파일을 volume을 통해 참조하고 있고 전부 docker compose에 의해 하나의 네트워크로 묶여있습니다.

``` yaml
version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - ~/datas/redis/:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    container_name: redis_container

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    container_name: logstash_container

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ~/datas/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch_container

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    container_name: kibana_container
```

메모리를 CPU가 여유롭게 사용하는 방법에는 크게 두가지가 있다고 판단됩니다.
1. HDD의 일부를 메모리처럼 사용하는 메모리 Swap
2. HDD & 메모리 실제로 증설 (서버의 환경이 클라우드 시스템이므로 손쉬움)

이 방법들을 고려하면서 이슈를 풀어나가보겠습니다.

- [x] #2
